name: SpeedrunAssistant
main: com.troy.speed.SpeedrunAssistant
version: 1.16.5-0.1.0
author: Troy Neubauer
api-version: 1.16
commands:
   regen:
      description: Regenerates the world, nether and end using a new random seed
      usage:
         /regen list - lists the current worlds (usually for debuging)
         /regen apply - moves all players to the new world
         /regen prep - prepares a new world that is activated when /regen apply is run
      permission-message: You don't have <permission>
